### ISSUE TITLE
Variables podman_playbook.yml

### ISSUE THREAD

**Issue by rlopez133** [hybrid-cloud-patterns/ansible-edge-gitops#22]
In a perfect world, a user should never need to modify a playbook and instead would pass `-e` and a file or specific variables.

The variables in the below file, I would instead have these as defaults within the defaults/main.yml of the container lifecycle role. 

And if it requires modification from the user, user should run the playbook with a `-e` and pass a file with their mods. 

https://github.com/hybrid-cloud-patterns/ansible-edge-gitops/blob/main/ansible/podman_playbook.yml#L6-L12

**Comment by mhjacks** [comment]
The container_lifecycle role seems like it's intended to be more generic than for this specific use case. As such, it seems like the use of vars in the playbook is appropriate to override and drive the behavior of the container_lifecycle role. The playbook-level vars can still be overridden via -e (in the various ways that can be done - an expecially interesting application of the open-ended Credential Types).  What do you think?

**Comment by rlopez133** [comment]
I'm not against it. It was more of a suggestion what I sent above. :)

**Comment by mhjacks** [comment]
Fair enough.  Thanks!
